
import { StockHolding } from './types';

export const INITIAL_HOLDINGS: StockHolding[] = [
  {
    id: '1',
    ticker: 'AAPL',
    name: '애플',
    shares: 10,
    avgPrice: 150,
    currentPrice: 185.4,
    dividendPerShare: 1.00,
    dividendYield: 0.54,
    frequency: 'Quarterly',
    purchaseDate: '2023-05-15',
    exchangeRateAtPurchase: 1320,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    ticker: 'KO',
    name: '코카콜라',
    shares: 25,
    avgPrice: 55,
    currentPrice: 60.12,
    dividendPerShare: 1.94,
    dividendYield: 3.23,
    frequency: 'Quarterly',
    purchaseDate: '2022-10-10',
    exchangeRateAtPurchase: 1430,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    ticker: 'O',
    name: '리얼티 인컴',
    shares: 50,
    avgPrice: 52,
    currentPrice: 54.80,
    dividendPerShare: 3.12,
    dividendYield: 5.69,
    frequency: 'Monthly',
    purchaseDate: '2024-01-20',
    exchangeRateAtPurchase: 1340,
    lastUpdated: new Date().toISOString(),
  }
];

export const MONTHS = {
  en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  ko: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']
};

export const TRANSLATIONS = {
  en: {
    appSubtitle: "Tracking your miniature empire's wealth",
    addAsset: "Add Tiny Asset",
    totalMarketValue: "Total Market Value",
    profit: "Profit",
    annualPassiveIncome: "Annual Passive Income",
    avgMonthly: "Avg Monthly",
    yieldOnCost: "Dividend Yield",
    activeTickers: "Active Tickers",
    aiInsights: "Tiny AI Assistant Insights",
    aiDescription: "Add assets to your miniature city to unlock AI financial forecasting.",
    monthlyPayouts: "Monthly Payouts",
    estimatedProjections: "Estimated Projections",
    tinyAllocation: "Tiny Allocation",
    portfolioTitle: "Your Tiny Portfolio",
    assetsTracked: "Assets Tracked",
    assetHeader: "Asset",
    holdingsHeader: "Holdings",
    marketPriceHeader: "Market Price",
    divYieldHeader: "Div. Yield",
    annualIncomeHeader: "Annual Income",
    actionsHeader: "Actions",
    emptyState: "Your miniature portfolio is empty.",
    startBuilding: "Start building your tiny empire",
    modalTitle: "Add New Tiny Asset",
    tickerLabel: "Ticker Symbol",
    sharesLabel: "Shares",
    avgPriceLabel: "Avg Price ($)",
    purchaseDateLabel: "Purchase Date",
    discoverButton: "Discover & Add Asset",
    safetyScore: "Safety Score",
    growthOutlook: "Growth Outlook",
    efficiencyMsg: "Efficiency of your capital",
    diversifiedMsg: "Diversified holdings",
    currencyToggle: "Currency"
  },
  ko: {
    appSubtitle: "내 자산과 배당금을 관리하세요",
    addAsset: "자산 추가하기",
    totalMarketValue: "총 시장 가치",
    profit: "수익",
    annualPassiveIncome: "연간 배당 수익",
    avgMonthly: "월평균 수익",
    yieldOnCost: "배당수익률",
    activeTickers: "보유 종목 수",
    aiInsights: "타이니 AI 분석 결과",
    aiDescription: "종목을 추가하면 AI가 자산 현황을 분석해 드립니다.",
    monthlyPayouts: "월별 배당금 지급 현황",
    estimatedProjections: "예상 배당금",
    tinyAllocation: "자산 배분 현황",
    portfolioTitle: "나의 포트폴리오",
    assetsTracked: "개 종목 관리 중",
    assetHeader: "종목",
    holdingsHeader: "보유 수량",
    marketPriceHeader: "현재가",
    divYieldHeader: "배당률",
    annualIncomeHeader: "연간 배당금",
    actionsHeader: "작업",
    emptyState: "포트폴리오가 비어 있습니다.",
    startBuilding: "당신만의 작은 제국을 건설해보세요",
    modalTitle: "새로운 자산 추가",
    tickerLabel: "티커 심볼",
    sharesLabel: "주식 수",
    avgPriceLabel: "평균 단가 ($)",
    purchaseDateLabel: "매수 날짜",
    discoverButton: "검색 및 추가",
    safetyScore: "안전 점수",
    growthOutlook: "성장 전망",
    efficiencyMsg: "자본 효율성 지표",
    diversifiedMsg: "다각화된 포트폴리오",
    currencyToggle: "통화"
  }
};
